Repository popcorndao/sweet-caramel, pull requests merged in 2021-12, with the labels that each got.

#39 ui polish for staking/claiming
  packages/app/components/ClaimCard.tsx
  packages/app/components/Common/TokenInput.tsx
  packages/app/components/MainActionButton.tsx
  packages/app/components/StakeCard.tsx
  packages/app/components/StakeClaimCard.tsx
  packages/app/components/StakingCardsList.tsx
  packages/app/components/TokenIcon.tsx
  packages/app/components/TokenInputToggle.tsx
  packages/app/pages/rewards.tsx
  packages/app/pages/staking/[id].tsx
  packages/app/pages/staking/index.tsx
  packages/app/public/images/claimCat.svg
  packages/app/styles/globals.css
  packages/app/tailwind.config.js
  packages/hardhat/deployments/kovan/POP.json
  packages/hardhat/deployments/localhost/ACLRegistry.json
  packages/hardhat/deployments/localhost/ContractRegistry.json
  packages/hardhat/deployments/localhost/POP.json
  packages/hardhat/deployments/localhost/POP_ETH_LP.json
  packages/hardhat/deployments/localhost/PopStaking.json
  packages/hardhat/deployments/localhost/TestPOP.json
  packages/hardhat/deployments/localhost/butterStaking.json
  packages/hardhat/deployments/localhost/popEthLPStaking.json
  packages/hardhat/deployments/localhost/xPOP.json
  packages/utils/src/getStakingStats.ts
Labels: SweetCaramel, frontend

#47 Feature/butter popover
  packages/app/components/InfoIconWithModal.tsx
  packages/app/components/Modal/DualActionModal.tsx
  packages/app/components/Modal/DualActionWideModal.tsx
  packages/app/components/Modal/SingleActionModal.tsx
  packages/app/components/Modal/SingleActionModalContainer.tsx
  packages/app/components/NavBar/NavBar.tsx
  packages/app/context/Web3/contracts.tsx
  packages/app/pages/butter.tsx
  packages/app/pages/staking/[id].tsx
  packages/utils/src/getStakingStats.ts
Labels: SweetCaramel, frontend, SmartContracts

#61 fixed memory leak
  packages/app/components/StakeCard.tsx
  packages/app/context/Web3/contracts.tsx
  packages/app/pages/_app.tsx
  packages/app/pages/butter.tsx
  packages/app/pages/staking/[id].tsx
  packages/app/pages/staking/index.tsx
Labels: bug, SweetCaramel

#63 default network switcher
  packages/app/components/NavBar/NavBar.tsx
Labels: SweetCaramel, frontend

#53 [WIP] Feature/staking revisions
  packages/app/components/StakeCard.tsx
  packages/app/context/Web3/contracts.tsx
  packages/app/pages/rewards.tsx
  packages/app/pages/staking/[id].tsx
  packages/hardhat/contracts/core/dao/LockStaking.sol
  packages/hardhat/contracts/core/dao/RewardsEscrow.sol
  packages/hardhat/contracts/core/dao/Staking.sol
  packages/hardhat/contracts/core/interfaces/IStaking.sol
  packages/hardhat/test/LockStaking.test.ts
  packages/hardhat/test/RewardsEscrow.test.ts
  packages/utils/src/contractHelpers.ts
  packages/utils/src/getStakingStats.ts
  packages/utils/src/types/index.ts
Labels: SweetCaramel, SmartContracts

#75 added real butter apy
  packages/app/pages/butter.tsx
Labels: SweetCaramel

#79 Add icons
  packages/app/components/BatchButter/SelectToken.tsx
  packages/app/components/BatchButter/TokenInput.tsx
  packages/app/pages/butter.tsx
  packages/app/public/images/tokens/3crv.png
  packages/app/public/images/tokens/butter.png
  packages/app/public/images/tokens/dai.webp
  packages/app/public/images/tokens/usdc.webp
  packages/app/public/images/tokens/usdt.webp
Labels: SweetCaramel, frontend

#70 Feature/get named addresses
  packages/app/components/Common/TokenInput.tsx
  packages/app/components/StakeCard.tsx
  packages/app/context/Web3/contracts.tsx
  packages/app/pages/butter.tsx
  packages/app/pages/staking/[id].tsx
  packages/app/pages/staking/index.tsx
  packages/hardhat/deploy/00_setup.ts
  packages/hardhat/deploy/03_LBPManager.ts
  packages/hardhat/deploy/06_Staking.ts
  packages/hardhat/deploy/07_ButterBatch.ts
  packages/hardhat/deployments/localhost/ButterBatch.json
  packages/hardhat/deployments/localhost/ButterBatchZapper.json
  packages/hardhat/deployments/localhost/Faucet.json
  packages/hardhat/deployments/localhost/LBPManager.json
  packages/hardhat/deployments/localhost/POP_ETH_LP.json
  packages/hardhat/deployments/localhost/PopStaking.json
  packages/hardhat/deployments/localhost/RewardsEscrow.json
  packages/hardhat/deployments/localhost/Superseeder.json
  packages/hardhat/deployments/localhost/TestPOP.json
  packages/hardhat/deployments/localhost/XPop.json
  packages/hardhat/deployments/localhost/butterStaking.json
  packages/hardhat/deployments/localhost/popEthLPStaking.json
  packages/hardhat/lib/adapters/ButterBatchAdapter.ts
  packages/hardhat/lib/external/SetToken/Configuration.ts
  packages/hardhat/lib/tasks/LBP/deploy.ts
  packages/hardhat/lib/tasks/airdrop/create.ts
  packages/hardhat/lib/utils/constants.ts
  packages/hardhat/lib/utils/getContractAddresses.ts
  packages/hardhat/lib/utils/getNamedAccounts.ts
  packages/hardhat/lib/utils/getStakingPools.ts
  packages/hardhat/test/fork/BalancerMerkleOrchard.test.ts
  packages/hardhat/test/fork/LBP-mainnet.test.ts
  packages/hardhat/test/fork/LBP-polygon.test.ts
  packages/utils/src/constants/index.ts
  packages/utils/src/getStakingStats.ts
  packages/utils/src/types/index.ts
Labels: SweetCaramel, frontend, SmartContracts

#62 added frontend deploy tag
  packages/hardhat/deploy/01_ACLRegistry.ts
  packages/hardhat/deploy/01_TestTokens.ts
  packages/hardhat/deploy/02_ContractRegistry.ts
  packages/hardhat/deploy/03_KeeperIncentive.ts
  packages/hardhat/deploy/04_TestToken.ts
  packages/hardhat/deploy/05_RewardsEscrow.ts
  packages/hardhat/deploy/06_Staking.ts
  packages/hardhat/deploy/07_ButterBatch.ts
  packages/hardhat/lib/external/SetToken/SetTokenManager.ts
  packages/hardhat/lib/external/SetToken/utils/getCreatedSetTokenAddress.ts
Labels: SweetCaramel, SmartContracts

#76 Feature/pausable butter
  packages/app/context/Web3/contracts.tsx
  packages/hardhat/contracts/core/defi/butter/ButterBatchProcessing.sol
  packages/hardhat/contracts/core/defi/butter/ButterBatchProcessingZapper.sol
  packages/hardhat/contracts/core/interfaces/IButterBatchProcessing.sol
  packages/hardhat/contracts/core/utils/KeeperIncentive.sol
  packages/hardhat/contracts/mocks/MockBasicIssuanceModule.sol
  packages/hardhat/contracts/mocks/MockCurveMetapool.sol
  packages/hardhat/contracts/mocks/MockCurveThreepool.sol
  packages/hardhat/contracts/mocks/MockYearnV2Vault.sol
  packages/hardhat/contracts/test_helpers/KeeperIncentiveHelper.sol
  packages/hardhat/deploy/07_ButterBatch.ts
  packages/hardhat/deployments/localhost/ACLRegistry.json
  packages/hardhat/deployments/localhost/ButterBatch.json
  packages/hardhat/deployments/localhost/ButterBatchZapper.json
  packages/hardhat/deployments/localhost/ContractRegistry.json
  packages/hardhat/deployments/localhost/Faucet.json
  packages/hardhat/deployments/localhost/KeeperIncentive.json
  packages/hardhat/deployments/localhost/POP.json
  packages/hardhat/deployments/localhost/POP_ETH_LP.json
  packages/hardhat/deployments/localhost/PopStaking.json
  packages/hardhat/deployments/localhost/RewardsEscrow.json
  packages/hardhat/deployments/localhost/TestPOP.json
  packages/hardhat/deployments/localhost/USDC.json
  packages/hardhat/deployments/localhost/butterStaking.json
  packages/hardhat/deployments/localhost/popEthLPStaking.json
  packages/hardhat/deployments/localhost/solcInputs/7e2febe42e31b5c8a1426c36d61634ad.json
  packages/hardhat/test/ButterBatchProcessing.test.ts
  packages/hardhat/test/ButterBatchProcessingZapper.test.ts
  packages/hardhat/test/KeeperIncentives.test.ts
Labels: SweetCaramel, SmartContracts

#77 Feature/fork cvx locker
  packages/app/components/StakeCard.tsx
  packages/app/context/Web3/contracts.tsx
  packages/app/pages/rewards.tsx
  packages/app/pages/staking/[id].tsx
  packages/hardhat/.gitignore
  packages/hardhat/contracts/core/dao/LockStaking.sol
  packages/hardhat/contracts/core/dao/PopLocker.sol
  packages/hardhat/contracts/core/dao/RewardsEscrow.sol
  packages/hardhat/contracts/core/dao/Staking.sol
  packages/hardhat/contracts/core/dao/cvxLocker.sol
  packages/hardhat/contracts/core/interfaces/IRewardsEscrow.sol
  packages/hardhat/contracts/core/utils/KeeperIncentive.sol
  packages/hardhat/deploy/06_Staking.ts
  packages/hardhat/lib/utils/getStakingPools.ts
  packages/hardhat/test/LockStaking.test.ts
  packages/hardhat/test/PopLocker.test.ts
  packages/hardhat/test/RewardsEscrow.test.ts
  packages/utils/src/getStakingStats.ts
Labels: SweetCaramel, SmartContracts

#92 Feature/new claims integration
  packages/app/components/ClaimCard.tsx
  packages/app/components/NavBar/GrantsMenu.tsx
  packages/app/components/NavBar/NavBar.tsx
  packages/app/components/NavBar/NetworkOptionsMenu.tsx
  packages/app/components/NavBar/ProposalsMenu.tsx
  packages/app/components/Rewards/ClaimCard.tsx
  packages/app/components/Rewards/VestingRecord.tsx
  packages/app/context/Web3/connectors.tsx
  packages/app/context/Web3/contracts.tsx
  packages/app/context/Web3/networkSwitch.ts
  packages/app/hooks/useClaimEscrows.ts
  packages/app/hooks/useClaimStakingReward.ts
  packages/app/hooks/useGetStakingReward.ts
  packages/app/hooks/useGetUserEscrows.ts
  packages/app/hooks/useLockStakingPool.ts
  packages/app/hooks/useStakingPool.ts
  packages/app/hooks/useVestingEscrow.ts
  packages/app/package.json
  packages/app/pages/rewards.tsx
  packages/app/pages/staking/[id].tsx
  packages/app/public/images/claim/popover.svg
  packages/app/public/images/claims-cat.svg
  packages/app/public/images/popcorn-logo-circle-disabled.svg
  packages/app/public/images/popcorn-logo-circle.svg
  packages/app/tailwind.config.js
  packages/hardhat/.gitignore
  packages/hardhat/contracts/core/dao/cvxLocker.sol
  packages/hardhat/contracts/core/defi/butter/ButterBatchProcessing.sol
  packages/hardhat/contracts/core/utils/KeeperIncentive.sol
  packages/hardhat/deploy/04_TestToken.ts
  packages/hardhat/deploy/06_Staking.ts
  packages/hardhat/deploy/06_xPOP.ts
  packages/hardhat/hardhat.config.ts
  packages/hardhat/lib/tasks/index.ts
  packages/hardhat/lib/tasks/staking/get.ts
  packages/hardhat/lib/tasks/staking/index.ts
  packages/hardhat/lib/utils/getNamedAccounts.ts
  packages/hardhat/lib/utils/getStakingPools.ts
  packages/hardhat/test/ButterBatchProcessing.test.ts
  packages/hardhat/test/ButterBatchProcessingZapper.test.ts
  packages/hardhat/test/KeeperIncentives.test.ts
  packages/utils/src/getStakingStats.ts
  packages/utils/src/types/index.ts
  yarn.lock
Labels: SweetCaramel, frontend, SmartContracts
